# Nama workflow
name: Generate Snake Animation

# Kapan workflow ini dijalankan
on:
  schedule:
    # Berjalan setiap 6 jam
    - cron: '0 */6 * * *'
  # Memungkinkan untuk menjalankan secara manual dari tab Actions
  workflow_dispatch:

# Pekerjaan yang harus dilakukan
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout kode repositori Anda
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Gunakan action yang benar untuk membuat animasi ular
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # Gunakan nama pengguna GitHub Anda secara otomatis
          github_user_name: ${{ github.repository_owner }}
          # Nama file output yang akan dibuat
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 3. Dorong (push) file gambar yang baru dibuat ke branch 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          # Token ini disediakan secara otomatis oleh GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
